export const TITLE = {
  HOME: "Home",
  MY_SHOP: "My Shop",
  CATALOG: "Catalog",
  PRODUCTS: "Products",
  SHOP_SETTING: "Shop Setting",
  ORDERS: "Orders",
  APPOINTMENTS: "Appointments",
  OFFERS: "Offers",
  PROMOTIONS: "Promotions",
  POINTS_RULE: "Points Rule",
  COUPONS: "Coupons",
  VOUCHERS: "Vouchers",
  MARKETING: "Marketing",
  CAMPAIGN: "Campaign",
  BROADCAST: "Broadcast",
  AUTOMATION: "Automation",
  ANNOUNCEMENT: "Announcement",
  SURVEY: "Survey",
  REVIEWS: "Reviews",
  TEMPLATES: "Templates",
  QUERIES: "Queries",
  LEADS: "Leads",
  COMPLAINTS: "Complaints",
  CHATS: "Chats",
  CALLS: "Calls",
  CUSTOMERS: "Customers",
  TIER: "Tier",
  PAYMENT: "Payment",
  PAYMENT_HISTORY: "Payment History",
  PAYMENT_STATS: "Payment Stats",
  SEGMENTS: "Segments",
  CUSTOMER_TYPE: "Customer Type",
  SETTINGS: "Settings",
  LANGUAGE: "Language",
  LOCATION: "Location",
};
